/** Phase 34B Azure Speech fast-transcription + in-process runner limits. */

export const ROUTE_VOICE_TRANSCRIPTION_PROVIDER_NAME = 'AZURE_SPEECH' as const

/** Azure Speech to text REST — fast transcription (GA). */
export const AZURE_SPEECH_FAST_TRANSCRIBE_API_VERSION = '2025-10-15'
export const AZURE_SPEECH_FAST_TRANSCRIBE_PATH =
  '/speechtotext/transcriptions:transcribe'

export const ROUTE_VOICE_TRANSCRIPTION_MAX_TEXT_LENGTH = 8_000
export const ROUTE_VOICE_TRANSCRIPTION_MAX_SAFE_FAILURE_MESSAGE_LENGTH = 120

/** Bounded in-memory audio buffer per concurrent job (matches upload cap). */
export const ROUTE_VOICE_TRANSCRIPTION_MAX_AUDIO_BYTES = 10 * 1024 * 1024

export const ROUTE_VOICE_TRANSCRIPTION_TIMEOUT_MS_DEFAULT = 60_000
export const ROUTE_VOICE_TRANSCRIPTION_TIMEOUT_MS_MIN = 5_000
export const ROUTE_VOICE_TRANSCRIPTION_TIMEOUT_MS_MAX = 180_000

export const ROUTE_VOICE_TRANSCRIPTION_CONCURRENCY_DEFAULT = 1
export const ROUTE_VOICE_TRANSCRIPTION_CONCURRENCY_MIN = 1
export const ROUTE_VOICE_TRANSCRIPTION_CONCURRENCY_MAX = 2

export const ROUTE_VOICE_TRANSCRIPTION_MAX_ATTEMPTS_DEFAULT = 3
export const ROUTE_VOICE_TRANSCRIPTION_MAX_ATTEMPTS_MIN = 1
export const ROUTE_VOICE_TRANSCRIPTION_MAX_ATTEMPTS_MAX = 5

export const ROUTE_VOICE_TRANSCRIPTION_LEASE_SECONDS_DEFAULT = 600
export const ROUTE_VOICE_TRANSCRIPTION_LEASE_SECONDS_MIN = 120
export const ROUTE_VOICE_TRANSCRIPTION_LEASE_SECONDS_MAX = 900

/**
 * Lease must outlive provider timeout by at least this margin so expired leases
 * cannot reclaim a still-running Azure Speech request.
 */
export const ROUTE_VOICE_TRANSCRIPTION_LEASE_TIMEOUT_SAFETY_MARGIN_MS = 60_000

export const ROUTE_VOICE_TRANSCRIPTION_RECOVERY_BATCH_DEFAULT = 25
export const ROUTE_VOICE_TRANSCRIPTION_RECOVERY_BATCH_MIN = 1
export const ROUTE_VOICE_TRANSCRIPTION_RECOVERY_BATCH_MAX = 100

/** Acceptance-probe prefix only (never a production route/report blob path). */
export const ROUTE_VOICE_ACCEPTANCE_PROBE_BLOB_PREFIX =
  '_acceptance-tests/voice-reports/' as const

/** Transient retry base delay (ms); exponential with attempt index. */
export const ROUTE_VOICE_TRANSCRIPTION_RETRY_BASE_DELAY_MS = 2_000
export const ROUTE_VOICE_TRANSCRIPTION_RETRY_MAX_DELAY_MS = 30_000

/**
 * When Azure audio duration differs from client-declared by more than this
 * fraction, emit a diagnostic only (never fail the transcription).
 */
export const ROUTE_VOICE_TRANSCRIPTION_DURATION_MISMATCH_RATIO = 0.35

export const ROUTE_VOICE_TRANSCRIPTION_EVENT_TYPE_PENDING =
  'ROUTE_VOICE_REPORT_TRANSCRIPTION_PENDING' as const
export const ROUTE_VOICE_TRANSCRIPTION_EVENT_TYPE_PROCESSING =
  'ROUTE_VOICE_REPORT_TRANSCRIPTION_PROCESSING' as const
export const ROUTE_VOICE_TRANSCRIPTION_EVENT_TYPE_COMPLETED =
  'ROUTE_VOICE_REPORT_TRANSCRIPTION_COMPLETED' as const
export const ROUTE_VOICE_TRANSCRIPTION_EVENT_TYPE_FAILED =
  'ROUTE_VOICE_REPORT_TRANSCRIPTION_FAILED' as const
export const ROUTE_VOICE_TRANSCRIPTION_EVENT_TYPE_RETRIED =
  'ROUTE_VOICE_REPORT_TRANSCRIPTION_RETRIED' as const

/** Stable safe failure codes (never Azure raw messages). */
export const RouteVoiceTranscriptionFailureCode = {
  NOT_CONFIGURED: 'ROUTE_VOICE_TRANSCRIPTION_NOT_CONFIGURED',
  NOT_FOUND: 'ROUTE_VOICE_TRANSCRIPTION_NOT_FOUND',
  FORBIDDEN: 'ROUTE_VOICE_TRANSCRIPTION_FORBIDDEN',
  ALREADY_COMPLETED: 'ROUTE_VOICE_TRANSCRIPTION_ALREADY_COMPLETED',
  ALREADY_PROCESSING: 'ROUTE_VOICE_TRANSCRIPTION_ALREADY_PROCESSING',
  RETRY_NOT_ALLOWED: 'ROUTE_VOICE_TRANSCRIPTION_RETRY_NOT_ALLOWED',
  AUDIO_MISSING: 'ROUTE_VOICE_TRANSCRIPTION_AUDIO_MISSING',
  AUDIO_UNSUPPORTED: 'ROUTE_VOICE_TRANSCRIPTION_AUDIO_UNSUPPORTED',
  NO_SPEECH: 'ROUTE_VOICE_TRANSCRIPTION_NO_SPEECH',
  PROVIDER_TIMEOUT: 'ROUTE_VOICE_TRANSCRIPTION_PROVIDER_TIMEOUT',
  PROVIDER_THROTTLED: 'ROUTE_VOICE_TRANSCRIPTION_PROVIDER_THROTTLED',
  PROVIDER_UNAVAILABLE: 'ROUTE_VOICE_TRANSCRIPTION_PROVIDER_UNAVAILABLE',
  PROVIDER_REJECTED: 'ROUTE_VOICE_TRANSCRIPTION_PROVIDER_REJECTED',
  RESULT_INVALID: 'ROUTE_VOICE_TRANSCRIPTION_RESULT_INVALID',
  FAILED: 'ROUTE_VOICE_TRANSCRIPTION_FAILED',
} as const

export type RouteVoiceTranscriptionFailureCodeValue =
  (typeof RouteVoiceTranscriptionFailureCode)[keyof typeof RouteVoiceTranscriptionFailureCode]
