export const PUB_SUB = Symbol('PUB_SUB')

export const ORDER_CREATED_EVENT = 'ORDER_CREATED'
export const ORDER_UPDATED_EVENT = 'ORDER_UPDATED'
export const NOTIFICATION_RECEIVED_EVENT = 'NOTIFICATION_RECEIVED'
export const ADMIN_OPERATIONS_FEED_EVENT = 'ADMIN_OPERATIONS_FEED'
export const BEZORGER_ROUTE_UPDATED_EVENT = 'BEZORGER_ROUTE_UPDATED'
