/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommonAppShell: typeof import('./src/components/common/CommonAppShell.vue')['default']
    CommonEmptyState: typeof import('./src/components/common/CommonEmptyState.vue')['default']
    CommonErrorState: typeof import('./src/components/common/CommonErrorState.vue')['default']
    CommonLoadingSkeleton: typeof import('./src/components/common/CommonLoadingSkeleton.vue')['default']
    CommonOfflineBanner: typeof import('./src/components/common/CommonOfflineBanner.vue')['default']
    CommonPermissionDenied: typeof import('./src/components/common/CommonPermissionDenied.vue')['default']
    FeatureAdminLayout: typeof import('./src/components/feature/admin/FeatureAdminLayout.vue')['default']
    FeatureApothekerLayout: typeof import('./src/components/feature/apotheker/FeatureApothekerLayout.vue')['default']
    FeatureAuthLayout: typeof import('./src/components/feature/auth/FeatureAuthLayout.vue')['default']
    FeatureBezorgerLayout: typeof import('./src/components/feature/bezorger/FeatureBezorgerLayout.vue')['default']
    FeatureProfileLayout: typeof import('./src/components/feature/profile/FeatureProfileLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAlert: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    USkeleton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
  }
}
