import { PDFDocument, PDFRawStream, decodePDFRawStream } from 'pdf-lib'
import { ObjectId } from 'mongodb'

import { OrderStatus } from '../../order/order-status.enum'
import { UserRole } from '../../user/user-role.enum'
import { RouteStatus } from '../route-status.enum'
import { DeliveryStopQrImageService } from '../qr/delivery-stop-qr-image.service'
import { DELIVERY_MANIFEST_LABELS_EN } from './delivery-manifest.labels.en'
import { DeliveryManifestPdfService } from './delivery-manifest-pdf.service'
import {
  buildRouteManifestFilename,
  buildStopManifestFilename,
} from './delivery-manifest.filename'
import type { RouteManifestData } from './delivery-manifest.types'
import { DELIVERY_MANIFEST_APPLICATION_NAME } from './delivery-manifest.constants'

function decodePdfContentOperators(content: string): string {
  const fromHex = content.replace(/<([0-9A-Fa-f\s]+)>/g, (_match, hex: string) => {
    try {
      return Buffer.from(hex.replace(/\s/g, ''), 'hex').toString('latin1')
    } catch {
      return ''
    }
  })

  return fromHex.replace(/\((?:\\.|[^\\)])*\)/g, match => {
    const inner = match.slice(1, -1)
    return inner
      .replace(/\\n/g, '\n')
      .replace(/\\r/g, '\r')
      .replace(/\\t/g, '\t')
      .replace(/\\\(/g, '(')
      .replace(/\\\)/g, ')')
      .replace(/\\\\/g, '\\')
  })
}

/**
 * Decode Flate content streams and expand PDF hex/literal string operators.
 */
async function extractPdfSearchText(bytes: Buffer): Promise<string> {
  const doc = await PDFDocument.load(bytes)
  const parts: string[] = [bytes.toString('latin1')]

  for (const [, obj] of doc.context.enumerateIndirectObjects()) {
    if (!(obj instanceof PDFRawStream)) {
      continue
    }
    try {
      const decoded = decodePDFRawStream({
        dict: obj.dict,
        contents: obj.contents,
      } as never) as unknown as {
        getBytes: (length: number) => Uint8Array
        bufferLength: number
      }
      const raw = decoded.getBytes(decoded.bufferLength)
      const latin1 = Buffer.from(raw).toString('latin1')
      parts.push(latin1)
      parts.push(decodePdfContentOperators(latin1))
    } catch {
      // ignore undecodable streams (e.g. image XObjects)
    }
  }

  return parts.join('\n')
}

function pdfEmbedsImage(bytes: Buffer): boolean {
  const text = bytes.toString('latin1')
  return text.includes('/Subtype /Image') || text.includes('/XObject')
}

function baseManifest(
  overrides?: Partial<RouteManifestData>,
): RouteManifestData {
  return {
    scope: 'ROUTE',
    routeId: new ObjectId().toString(),
    routeDate: '2026-07-26',
    routeStatus: RouteStatus.ASSIGNED,
    routeCancelled: false,
    generatedAt: new Date('2026-07-26T12:00:00.000Z'),
    generatedBy: {
      userId: new ObjectId().toString(),
      role: UserRole.ADMIN,
    },
    assignedCourier: {
      displayName: 'Courier One',
      profileId: new ObjectId().toString(),
    },
    stopCount: 1,
    totalOrderCount: 1,
    totalLineCount: 1,
    totalItemQuantity: 10,
    stops: [
      {
        stopId: 'stop-1',
        sequence: 1,
        pharmacy: {
          name: 'Apotheek Noord',
          addressLine: 'Kerkstraat 1',
          postalCode: '8000',
          city: 'Brugge',
        },
        stopStatus: 'pending',
        orders: [
          {
            orderId: new ObjectId().toString(),
            orderStatus: OrderStatus.PLANNED,
            deliveryDate: '2026-07-26',
            lines: [
              {
                vaccineId: new ObjectId().toString(),
                vaccineName: 'Comirnaty',
                quantity: 10,
              },
            ],
            lineCount: 1,
            itemQuantity: 10,
          },
        ],
        totals: { orderCount: 1, lineCount: 1, itemQuantity: 10 },
        arrival: null,
        deliveryProof: null,
        qr: { available: false, state: 'UNAVAILABLE', pngBytes: null },
      },
    ],
    ...overrides,
  }
}

describe('DeliveryManifestPdfService', () => {
  const pdfService = new DeliveryManifestPdfService()
  const qrImageService = new DeliveryStopQrImageService()

  it('21: generated bytes begin with valid PDF signature', async () => {
    const bytes = await pdfService.render(baseManifest())
    expect(bytes.subarray(0, 5).toString('utf8')).toBe('%PDF-')
  })

  it('22: PDF contains route title/date/status', async () => {
    const bytes = await pdfService.render(baseManifest())
    const text = await extractPdfSearchText(bytes)
    expect(text).toContain(DELIVERY_MANIFEST_LABELS_EN.title)
    expect(text).toContain('2026-07-26')
    expect(text).toContain(RouteStatus.ASSIGNED)
  })

  it('23: PDF contains every expected pharmacy for full route', async () => {
    const bytes = await pdfService.render(
      baseManifest({
        stopCount: 2,
        totalOrderCount: 2,
        totalLineCount: 2,
        totalItemQuantity: 15,
        stops: [
          {
            ...baseManifest().stops[0],
            sequence: 1,
            pharmacy: {
              name: 'Apotheek Alpha',
              addressLine: 'Street 1',
              postalCode: '1000',
              city: 'Brussel',
            },
          },
          {
            ...baseManifest().stops[0],
            stopId: 'stop-2',
            sequence: 2,
            pharmacy: {
              name: 'Apotheek Beta',
              addressLine: 'Street 2',
              postalCode: '2000',
              city: 'Antwerpen',
            },
            orders: [
              {
                orderId: new ObjectId().toString(),
                orderStatus: OrderStatus.PLANNED,
                deliveryDate: '2026-07-26',
                lines: [
                  {
                    vaccineId: new ObjectId().toString(),
                    vaccineName: 'Spikevax',
                    quantity: 5,
                  },
                ],
                lineCount: 1,
                itemQuantity: 5,
              },
            ],
            totals: { orderCount: 1, lineCount: 1, itemQuantity: 5 },
          },
        ],
      }),
    )
    const text = await extractPdfSearchText(bytes)
    expect(text).toContain('Apotheek Alpha')
    expect(text).toContain('Apotheek Beta')
  })

  it('24: stop-scoped PDF contains only owning pharmacy', async () => {
    const bytes = await pdfService.render(
      baseManifest({
        scope: 'STOP',
        assignedCourier: null,
        stopCount: 1,
        stops: [
          {
            ...baseManifest().stops[0],
            pharmacy: {
              name: 'Only Mine',
              addressLine: 'Main 1',
              postalCode: '9000',
              city: 'Gent',
            },
          },
        ],
      }),
    )
    const text = await extractPdfSearchText(bytes)
    expect(text).toContain('Only Mine')
    expect(text).not.toContain('Secret Pharmacy')
  })

  it('25: vaccine names and quantities appear', async () => {
    const bytes = await pdfService.render(baseManifest())
    const text = await extractPdfSearchText(bytes)
    expect(text).toContain('Comirnaty')
    expect(text).toContain('10')
  })

  it('26: multi-page output works', async () => {
    const manyOrders = Array.from({ length: 40 }, (_, i) => ({
      orderId: new ObjectId().toString(),
      orderStatus: OrderStatus.PLANNED,
      deliveryDate: '2026-07-26',
      lines: [
        {
          vaccineId: new ObjectId().toString(),
          vaccineName: `VaccineLine${i}`,
          quantity: i + 1,
        },
      ],
      lineCount: 1,
      itemQuantity: i + 1,
    }))

    const bytes = await pdfService.render(
      baseManifest({
        totalOrderCount: manyOrders.length,
        totalLineCount: manyOrders.length,
        totalItemQuantity: manyOrders.reduce((s, o) => s + o.itemQuantity, 0),
        stops: [
          {
            ...baseManifest().stops[0],
            orders: manyOrders,
            totals: {
              orderCount: manyOrders.length,
              lineCount: manyOrders.length,
              itemQuantity: manyOrders.reduce((s, o) => s + o.itemQuantity, 0),
            },
          },
        ],
      }),
    )

    const doc = await PDFDocument.load(bytes)
    expect(doc.getPageCount()).toBeGreaterThan(1)
  })

  it('27: long order list does not corrupt PDF', async () => {
    const lines = Array.from({ length: 80 }, (_, i) => ({
      vaccineId: new ObjectId().toString(),
      vaccineName: `LongVaccineNameNumber${i}`,
      quantity: 1,
    }))
    const bytes = await pdfService.render(
      baseManifest({
        totalLineCount: lines.length,
        totalItemQuantity: lines.length,
        stops: [
          {
            ...baseManifest().stops[0],
            orders: [
              {
                orderId: new ObjectId().toString(),
                orderStatus: OrderStatus.PLANNED,
                deliveryDate: '2026-07-26',
                lines,
                lineCount: lines.length,
                itemQuantity: lines.length,
              },
            ],
            totals: {
              orderCount: 1,
              lineCount: lines.length,
              itemQuantity: lines.length,
            },
          },
        ],
      }),
    )
    expect(bytes.subarray(0, 5).toString('utf8')).toBe('%PDF-')
    const doc = await PDFDocument.load(bytes)
    expect(doc.getPageCount()).toBeGreaterThan(0)
  })

  it('28: QR image is embedded for active stop', async () => {
    const png = await qrImageService.renderPngBuffer('manifest-test-token.sig')
    const bytes = await pdfService.render(
      baseManifest({
        stops: [
          {
            ...baseManifest().stops[0],
            qr: { available: true, state: 'ACTIVE', pngBytes: png },
          },
        ],
      }),
    )
    const text = await extractPdfSearchText(bytes)
    expect(pdfEmbedsImage(bytes)).toBe(true)
    expect(text).toContain(DELIVERY_MANIFEST_LABELS_EN.qrActive)
  })

  it('29: consumed stop has no active QR', async () => {
    const bytes = await pdfService.render(
      baseManifest({
        stops: [
          {
            ...baseManifest().stops[0],
            stopStatus: 'delivered',
            qr: { available: false, state: 'CONSUMED', pngBytes: null },
            deliveryProof: {
              method: 'QR',
              deliveredAt: new Date('2026-07-26T11:00:00.000Z'),
              courierDisplayName: 'Courier One',
              associatedOrderCount: 1,
              recipientCity: 'Brugge',
              confirmationReference: 'abc123',
            },
          },
        ],
      }),
    )
    const text = await extractPdfSearchText(bytes)
    expect(text).toContain(DELIVERY_MANIFEST_LABELS_EN.qrConsumed)
    expect(text).not.toContain(DELIVERY_MANIFEST_LABELS_EN.qrActive)
  })

  it('30: PDF metadata contains no secrets', async () => {
    const secretToken = 'super.secret.token-value'
    const png = await qrImageService.renderPngBuffer(secretToken)
    const bytes = await pdfService.render(
      baseManifest({
        stops: [
          {
            ...baseManifest().stops[0],
            qr: { available: true, state: 'ACTIVE', pngBytes: png },
          },
        ],
      }),
    )
    const doc = await PDFDocument.load(bytes)
    expect(doc.getTitle()).toBe(DELIVERY_MANIFEST_LABELS_EN.title)
    expect(doc.getSubject()).toBe(DELIVERY_MANIFEST_LABELS_EN.subject)
    expect(doc.getCreator()).toBe(DELIVERY_MANIFEST_APPLICATION_NAME)
    const text = await extractPdfSearchText(bytes)
    expect(text).not.toContain(secretToken)
    expect(text).not.toContain('nonceHash')
    expect(text).not.toContain('encodedToken')
  })
})

describe('delivery-manifest filename helpers', () => {
  it('31: output filename is safe', () => {
    const routeId = '507f1f77bcf86cd799439011'
    expect(buildRouteManifestFilename('2026-07-26', routeId)).toBe(
      'delivery-manifest-2026-07-26-route-99439011.pdf',
    )
    expect(buildStopManifestFilename('2026-07-26', routeId, 3)).toBe(
      'delivery-manifest-2026-07-26-route-99439011-stop-3.pdf',
    )
    expect(buildRouteManifestFilename('bad/date', routeId)).toContain(
      'unknown-date',
    )
    expect(buildRouteManifestFilename('2026-07-26', routeId)).not.toMatch(
      /[\\/:*?"<>|]/,
    )
  })
})
